stages:
  - test
  - deploy

.test-template:
  stage: test
  image: swamydev/geo-write:latest
  coverage: '/^TOTAL.+?(\d+\%)$/'
  tags:
    - python

test-main:
  extends: .test-template
  script:
    - pip install -e .[test]
    - make test
  rules:
    - if: '$CI_COMMIT_TAG == null'
      when: always

test-release:
  extends: .test-template
  script:
    - pip install -e .[test]
    - make test
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always

deploy-pypi:
  stage: deploy
  image: python:latest
  needs:
    - test-release
  script:
    - make dist
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
  tags:
    - python